# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Women in Engineering
email: webmaster@wiebristol.co.uk
description: Promoting gender equality in the Faculty of Engineering at the University of Bristol.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.wiebristol.co.uk" # the base hostname & protocol for your site
twitter_username: 
github_username:  wiebristol/wiebristol.github.io
facebook_username: womeninengbristol

# Build settings
markdown: kramdown
